title:            Dmytro Serdiuk's blog
description:      You'll see staff related to my work.
disqus_shortname: extsoft
reading_time:     true
words_per_minute: 100
# Your site's domain goes here (eg: https://mmistakes.github.io, http://yourdomain.com, etc)
# When testing locally leave blank or use http://localhost:4000
url: http://extsoft.pro

# Owner/author information
owner:
  name:           Dmytro Serdiuk
  avatar:         at-logo.png 
  bio:            "The passionate architect of quality solutions."
  email:          dmytro.serdiuk@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        DmytroSerdiuk
  facebook:       
  github:         extsoft
  stackexchange:  
  linkedin:       dserdiuk
  instagram:      
  flickr:         
  tumblr:         
  # google plus id, include the '+', eg +mmistakes
  google_plus:

# Background image to be tiled on all pages
background: 

# Analytics and webmaster tools stuff goes here
google_analytics:   
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Kiev
future:      false  # publish future dated posts --  true, false (default) 
highlighter: rouge
markdown:    kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

include: 
  - .htaccess
exclude: 
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README.md
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
  - docker-compose.yml
  - .travis.yml
  - id_rsa.enc

theme: jekyll-theme-architect
