version: '3'
services:
    check:
        image: extsoft/blog
        build: .
        command: "./preview.sh check"
        volumes:
            - .:/srv/jekyll
    preview:
        image: extsoft/blog
        build: .
        command: "./preview.sh preview"
        ports:
        - 4000:4000
        volumes:
        - .:/srv/jekyll